# File: netlify.toml (in your project's root folder)

[build]
  # This final command installs dependencies for both backend and frontend, then builds the frontend.
  command = "npm install --prefix backend && npm install --prefix frontend && CI=false npm run build --prefix frontend"
  
  # The directory where our serverless function code lives
  functions = "backend"
  
  # The directory Netlify will publish as the static site
  publish = "frontend/build"

# This section tells Netlify which version of Node.js to use for the build
[build.environment]
  NODE_VERSION = "18"

# This is the magic rule that makes your API work
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
